### ISSUE TITLE
 PHP Fatal Error – yii\base\ErrorException During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of lav45\settings\Settings::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/lav45/yii2-settings/src/Settings.php:265

### ISSUE THREAD

**Issue by maxodrom** [lav45/yii2-settings#6]
Привет!
Спасибо за расширение, стараюсь пользоваться.

Но возникла проблема из-за того, что класс Settings не совсем адекватно реализует интерфейс \ArrayAccess:

```
During inheritance of ArrayAccess: Uncaught yii\base\ErrorException: Return type of lav45\settings\Settings::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/lav45/yii2-settings/src/Settings.php:265
Stack trace:
#0 /app/vendor/lav45/yii2-settings/src/Settings.php(29): yii\base\ErrorHandler->handleError(8192, 'Return type of ...', '/app/vendor/lav...', 265)
#1 /app/vendor/yiisoft/yii2/BaseYii.php(293): include('/app/vendor/lav...')
#2 /app/controllers/TestController.php(56): yii\BaseYii::autoload('lav45\\settings\\...')
#3 [internal function]: app\controllers\TestController->actionSingletonConfig()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('singleton-confi...', Array)
#7 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('test/singleton-...', Array)
#8 /app/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(yii\web\Request))
#9 /app/web/index.php(16): yii\base\Application->run()
#10 {main}
```

Т.е. проблема здесь: https://github.com/lav45/yii2-settings/blob/c739037b282ba62918f3411eb93e33365b470800/src/Settings.php#L265

Вместо: 
```php
public function offsetGet($offset)
```
должно быть так: 
```php
public function offsetGet($offset): mixed
```

И это решает проблему.

Нельзя ли это пофиксить?

**Comment by lav45** [comment]
@maxodrom у меня прошли все тесты, но баг так и не удалось воспроизвести.
Какая у тебя версия php? Покажи пример кода как можно воспроизвести баг.

Ошибку поправил. Проверь на своём коде.

**Comment by maxodrom** [comment]
Спасибо, сейчас работает как надо!

Опишу вкратце, что я делал, чтобы воспроизвести ошибку:
- PHP 8.3
- yii2-app basic шаблон 
- стандартный Docker образ image: yiisoftware/yii2-php:8.3-apache

Далее в `config/web.php` я подключаю твой код не как компонент, а как синглтон, чтобы использовать механизм [Dependancy Injection](https://www.yiiframework.com/doc/guide/2.0/ru/concept-di-container): 
```php 

$params = require __DIR__ . '/params.php';
$db = require __DIR__ . '/db.php';
$mailer = require __DIR__ . '/mailer.php';

$config = [
    'id' => 'basic',
    // .... 
    'container' => [
        'definitions' => [
           // .... 
        ],
        'singletons' => [
            // see https://github.com/lav45/yii2-settings
            \lav45\settings\Settings::class => [
                'class' => \lav45\settings\Settings::class,
                // You can add an arbitrary prefix to all keys
                // 'keyPrefix' => 'key_',
                // DbStorage use as default storage
                //'storage' => [
                //    'class' => 'lav45\settings\storage\DbStorage',
                //    'tableName' => '{{%settings}}',
                //    'db' => 'db',
                //],
                'as cache' => [
                    'class' => \lav45\settings\behaviors\CacheBehavior::class,
                    'cache' => 'cache',
                    'cacheDuration' => 86400,
                ],
                'as access' => [
                    'class' => \lav45\settings\behaviors\QuickAccessBehavior::class,
                ],
                'as context' => [
                    'class' => \lav45\settings\behaviors\ContextBehavior::class,
                ],
            ],
        ],
    ],
    'components' => [
        // .... 
        ],
    ],
    'params' => $params,
    'modules' => [
        // ... 
    ],
];

return $config;
```

Для чего я так делаю? Мне просто удобно воспользоваться механикой внедрения зависимостей и например, в тех местах, где требуется обращение к классу Settings, я делаю следующее.

Например, создай в SiteController из коробки метод: 
```php
/**
     * Test UserPreferences model.
     * @return void
     */
    public function actionUserPreferences(Settings $settings): void
    {
        print_r($settings);
        exit;
    }
```

Внутри экшена, я уже могупользоваться твоим классом обычным образом: 
```php
$someValue = $settings->get('key');
```
Контейнер внедрения зависимости создаст мне объект класса Settings, потому что выше я сконфигурировал контейнер в настройках `config/web.php`.

Но в этом моменте и вылетала ошибка: 
![изображение](https://github.com/user-attachments/assets/3b90bd12-3d11-4351-84fb-3024b78f9a6a)

Скорее всего, это какие-то особенности версии PHP8.3. И должна быть реализована строгая сигнатура метода, С ЯВНЫМ УКАЗАНИЕМ возвращаемого типа `MIXED`. (https://www.php.net/manual/ru/arrayaccess.offsetget.php)
```php
public ArrayAccess::offsetGet(mixed $offset): mixed
```

Все вставало на места, если исправить это в исходнике твоего кода.

В последнем фиксе ты прописал это как атрибут:
```php
    /**
     * @inheritDoc
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->get($offset);
    }
```

Но можно просто и так:

```php
    /**
     * @inheritDoc
     */
    public function offsetGet($offset): mixed
    {
        return $this->get($offset);
    }
```
